'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {products,money} from '../lib/catalog';
type Inventory={id:string;price:number;stock:number;active:boolean};
type Order={id:string;name:string;email:string;phone:string;total:number;status:string;fulfillment_status:string;created_at:string;items:{id:string;name:string;quantity:number}[]};
export default function Admin(){const [authenticated,setAuthenticated]=useState(false);const [inventory,setInventory]=useState<Inventory[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
async function load(){const response=await fetch('/api/admin');const data=await response.json();if(response.ok){setAuthenticated(true);setInventory(data.inventory);setOrders(data.orders);}else if(response.status===401)setAuthenticated(false);else setError(data.error);}
useEffect(()=>{load().catch(()=>setError('Não foi possível carregar.'));},[]);
async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const password=new FormData(e.currentTarget).get('password');const res=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const data=await res.json();if(!res.ok)throw new Error(data.error);await load();}catch(e){setError(e instanceof Error?e.message:'Falha de conexão.');}setBusy(false);}
async function save(body:unknown){setBusy(true);setError('');try{const res=await fetch('/api/admin',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error);await load();}catch(e){setError(e instanceof Error?e.message:'Falha ao salvar.');}setBusy(false);}
return <main className="admin wrap"><div className="section-heading"><div><Link className="brand" href="/"><span>icc.</span></Link><h1>Gestão da loja</h1></div>{authenticated&&<button className="button light" onClick={async()=>{await fetch('/api/admin/session',{method:'DELETE'});setAuthenticated(false);setInventory([]);setOrders([]);}}>Sair</button>}</div>{error&&<p className="error" role="alert">{error}</p>}{!authenticated?<form className="admin-login" onSubmit={login}><h2>Acesso da equipe ICC</h2><label>Senha administrativa<input name="password" type="password" required autoComplete="current-password" minLength={16}/></label><button className="button green" disabled={busy}>{busy?'Entrando…':'Entrar'}</button><p className="muted">O acesso é habilitado após a configuração do banco e das credenciais da loja.</p><Link className="text-link" href="/">Voltar para a loja</Link></form>:<><h2>Estoque disponível</h2><p className="muted">Informe unidades disponíveis para novas reservas. As unidades de pedidos pendentes já foram descontadas. Os preços devem ser alterados no catálogo e no banco pelo responsável.</p><div className="admin-inventory">{inventory.map(p=><form key={p.id} onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);save({kind:'inventory',id:p.id,stock:Number(data.get('stock')),active:data.get('active')==='on'});}}><h3>{products.find(x=>x.id===p.id)?.name||p.id}</h3><p>{money(p.price)}</p><label>Unidades disponíveis<input name="stock" type="number" min="0" max="100000" required defaultValue={p.stock}/></label><label className="radio"><input name="active" type="checkbox" defaultChecked={p.active}/>Disponível para venda</label><button className="button light" disabled={busy}>Salvar estoque</button></form>)}</div><div className="section-heading"><h2>Últimos pedidos</h2><button className="button light" onClick={()=>load()} disabled={busy}>Atualizar</button></div>{!orders.length&&<p>Nenhum pedido online registrado.</p>}<div className="admin-orders">{orders.map(o=><article key={o.id}><div className="summary-row"><h3>{o.name}</h3><strong>{money(o.total)}</strong></div><p className="muted">{new Date(o.created_at).toLocaleString('pt-BR')} • {o.id}</p><p>{o.email}<br/>{o.phone}</p><ul>{o.items.map(i=><li key={i.id}>{i.quantity}× {i.name}</li>)}</ul><span className="admin-status">{o.status==='paid'?'Pagamento confirmado':o.status==='cancelled'?'Cancelado':'Aguardando pagamento'}</span>{o.status==='paid'&&<label>Preparação <select value={o.fulfillment_status} disabled={busy} onChange={e=>save({kind:'order',id:o.id,fulfillment:e.target.value})}><option value="new">Novo</option><option value="preparing">Em preparação</option><option value="ready">Pronto para retirada</option><option value="collected">Retirado</option></select></label>}</article>)}</div></>}</main>;}
