export type Product = { id: string; name: string; category: 'tech' | 'papelaria'; type: string; price: number; image: string; badge?: string; description: string; specs: string[] };
const demonstration: Product[] = [
 {id:'headphone',name:'Headphone sem fio',category:'tech',type:'Áudio',price:18990,image:'/images/headphone.jpg',badge:'Para o seu setup',description:'Uma seleção de áudio para acompanhar trabalho, jogos e suas playlists. Modelo ilustrativo: confirme marca e disponibilidade com a ICC.',specs:['Categoria: fones de ouvido','Conectividade: confirmar com a loja','Imagem e preço demonstrativos']},
 {id:'teclado',name:'Teclado para o seu setup',category:'tech',type:'Periféricos',price:14990,image:'/images/keyboard.jpg',description:'Conforto para escrever e jogar. Consulte a equipe para encontrar o layout e o modelo ideais.',specs:['Categoria: teclados','Layout e conexão: consultar','Imagem e preço demonstrativos']},
 {id:'mouse',name:'Mouse para trabalho e jogos',category:'tech',type:'Periféricos',price:7990,image:'/images/mouse.jpg',badge:'Essencial',description:'Precisão no dia a dia. A equipe ajuda a escolher um mouse compatível com seu computador.',specs:['Categoria: mouses','DPI e conexão: consultar','Imagem e preço demonstrativos']},
 {id:'notebook',name:'Notebook para o dia a dia',category:'tech',type:'Computadores',price:289990,image:'/images/laptop.jpg',description:'Estudo, produtividade e entretenimento. Consulte configurações disponíveis na loja antes de comprar.',specs:['Categoria: notebooks','Memória e processador: consultar','Imagem e preço demonstrativos']},
 {id:'caderno',name:'Caderno espiral',category:'papelaria',type:'Cadernos',price:2490,image:'/images/notebook.jpg',badge:'Ideias no papel',description:'Seu próximo projeto começa em uma página em branco. Consulte capas, tamanhos e quantidade de folhas.',specs:['Categoria: cadernos','Formato e folhas: consultar','Imagem e preço demonstrativos']},
 {id:'kit-escrita',name:'Kit de escrita e organização',category:'papelaria',type:'Escrita',price:3490,image:'/images/stationery.jpg',description:'Uma seleção para organizar a mesa e colocar as ideias no papel. Itens do kit sujeitos à confirmação.',specs:['Categoria: escrita','Composição: consultar a loja','Imagem e preço demonstrativos']},
 {id:'lapis',name:'Lápis para escrever e desenhar',category:'papelaria',type:'Escrita',price:1290,image:'/images/pencils.jpg',description:'Materiais para estudos, esboços e criatividade. Consulte opções e marcas com a equipe.',specs:['Categoria: lápis','Quantidade e graduação: consultar','Imagem e preço demonstrativos']},
 {id:'planner',name:'Caderno de planejamento',category:'papelaria',type:'Organização',price:3990,image:'/images/planner.jpg',description:'Organize sua rotina com espaço para suas ideias. Consulte os modelos de organização disponíveis.',specs:['Categoria: organização','Modelo e tamanho: consultar','Imagem e preço demonstrativos']}
];
export const products: Product[] = [
{id:'rapoo',name:'Fone Headset Rapoo',category:'tech',type:'Headsets com fio',price:21990,image:'/images/rapoo.jpg',badge:'Do catálogo ICC',description:'Headset Rapoo do catálogo enviado pela loja. Consulte disponibilidade e especificações antes de confirmar seu pedido.',specs:['Preço do catálogo enviado: R$ 219,90','Marca: Rapoo','Modelo e disponibilidade: confirmar']},
{id:'gamer',name:'Fone Gamer para PC / PlayStation',category:'tech',type:'Headsets com fio',price:42900,image:'/images/gamer.jpg',description:'Fone gamer apresentado no catálogo ICC. O título está parcialmente cortado na captura; confirme o modelo e compatibilidade com a equipe.',specs:['Preço do catálogo: R$ 429,00','Nome completo: confirmar','Compatibilidade específica: confirmar']},
{id:'redragon',name:'Fone Gamer Redragon Nireus',category:'tech',type:'Headsets com fio',price:33490,image:'/images/redragon.jpg',badge:'Seu próximo setup',description:'Headset gamer Redragon Nireus apresentado no catálogo ICC. Consulte as características e a disponibilidade com a loja.',specs:['Preço do catálogo: R$ 334,90','Marca: Redragon • linha Nireus','Disponibilidade: confirmar']},
{id:'pcyes',name:'Teclado Mecânico KLR Pcyes',category:'tech',type:'Teclados mecânicos',price:33990,image:'/images/pcyes.jpg',description:'Teclado mecânico KLR Pcyes do catálogo ICC. Confirme layout, switches e compatibilidade antes do pedido.',specs:['Preço do catálogo: R$ 339,90','Marca: Pcyes','Layout e switches: confirmar']},
{id:'evolut',name:'Teclado Mecânico Evolut Pro…',category:'tech',type:'Teclados mecânicos',price:33990,image:'/images/evolut.jpg',description:'Teclado mecânico Evolut do catálogo ICC. O nome está parcialmente cortado na captura; consulte o modelo completo.',specs:['Preço do catálogo: R$ 339,90','Modelo completo: confirmar','Layout e switches: confirmar']},
{id:'tdagger',name:'Teclado Mecânico T-Dagger B…',category:'tech',type:'Teclados mecânicos',price:31990,image:'/images/tdagger.jpg',description:'Teclado mecânico T-Dagger do catálogo ICC. O nome está parcialmente cortado; consulte o modelo completo com a equipe.',specs:['Preço do catálogo: R$ 319,90','Modelo completo: confirmar','Layout e switches: confirmar']},
{id:'logitech',name:'Kit Logitech MK235',category:'tech',type:'Kits sem fio',price:18990,image:'/images/logitech.jpg',badge:'Trabalho sem fios',description:'Kit de teclado e mouse sem fio Logitech MK235 apresentado no catálogo ICC. Consulte disponibilidade e detalhes.',specs:['Preço do catálogo: R$ 189,90','Marca: Logitech • modelo MK235','Kit teclado e mouse sem fio']},
...demonstration.filter(p=>p.category==='papelaria')
];
export const money = (cents: number) => (cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export const whatsapp = process.env.NEXT_PUBLIC_WHATSAPP || '553591791821';
export const wa = (text:string) => `https://wa.me/${whatsapp}?text=${encodeURIComponent(text)}`;
export const maps = 'https://www.google.com/maps/search/?api=1&query=ICC+Shopping+da+Informática+Av.+Rui+Barbosa+76+Varginha';
