export type Product = { id: string; name: string; category: 'tech' | 'papelaria'; type: string; price: number; image: string; badge?: string; description: string; specs: string[]; imageSource?:string; imageNote?:string };
const demonstration: Product[] = [
 {id:'headphone',name:'Headphone sem fio',category:'tech',type:'Áudio',price:18990,image:'/images/headphone.jpg',badge:'Para o seu setup',description:'Uma seleção de áudio para acompanhar trabalho, jogos e suas playlists. Modelo ilustrativo: confirme marca e disponibilidade com a ICC.',specs:['Categoria: fones de ouvido','Conectividade: confirmar com a loja','Imagem e preço demonstrativos']},
 {id:'teclado',name:'Teclado para o seu setup',category:'tech',type:'Periféricos',price:14990,image:'/images/keyboard.jpg',description:'Conforto para escrever e jogar. Consulte a equipe para encontrar o layout e o modelo ideais.',specs:['Categoria: teclados','Layout e conexão: consultar','Imagem e preço demonstrativos']},
 {id:'mouse',name:'Mouse para trabalho e jogos',category:'tech',type:'Periféricos',price:7990,image:'/images/mouse.jpg',badge:'Essencial',description:'Precisão no dia a dia. A equipe ajuda a escolher um mouse compatível com seu computador.',specs:['Categoria: mouses','DPI e conexão: consultar','Imagem e preço demonstrativos']},
 {id:'notebook',name:'Notebook para o dia a dia',category:'tech',type:'Computadores',price:289990,image:'/images/laptop.jpg',description:'Estudo, produtividade e entretenimento. Consulte configurações disponíveis na loja antes de comprar.',specs:['Categoria: notebooks','Memória e processador: consultar','Imagem e preço demonstrativos']},
 {id:'caderno',name:'Caderno espiral',category:'papelaria',type:'Cadernos',price:2490,image:'/images/notebook.jpg',badge:'Ideias no papel',description:'Seu próximo projeto começa em uma página em branco. Consulte capas, tamanhos e quantidade de folhas.',specs:['Categoria: cadernos','Formato e folhas: consultar','Imagem e preço demonstrativos']},
 {id:'kit-escrita',name:'Kit de escrita e organização',category:'papelaria',type:'Escrita',price:3490,image:'/images/stationery.jpg',description:'Uma seleção para organizar a mesa e colocar as ideias no papel. Itens do kit sujeitos à confirmação.',specs:['Categoria: escrita','Composição: consultar a loja','Imagem e preço demonstrativos']},
 {id:'lapis',name:'Lápis para escrever e desenhar',category:'papelaria',type:'Escrita',price:1290,image:'/images/pencils.jpg',description:'Materiais para estudos, esboços e criatividade. Consulte opções e marcas com a equipe.',specs:['Categoria: lápis','Quantidade e graduação: consultar','Imagem e preço demonstrativos']},
 {id:'planner',name:'Caderno de planejamento',category:'papelaria',type:'Organização',price:3990,image:'/images/planner.jpg',description:'Organize sua rotina com espaço para suas ideias. Consulte os modelos de organização disponíveis.',specs:['Categoria: organização','Modelo e tamanho: consultar','Imagem e preço demonstrativos']}
];
export const products: Product[] = [
{id:'rapoo',name:'Fone Headset Rapoo',category:'tech',type:'Headsets com fio',price:21990,image:"/images/rapoo-hq.webp",imageSource:"https://rapoo.africa/product/h120/",imageNote:"Foto da linha Rapoo H120, identificada na embalagem. Confirme a variante com a ICC.",badge:'Do catálogo ICC',description:'Headset Rapoo do catálogo enviado pela loja. Consulte disponibilidade e especificações antes de confirmar seu pedido.',specs:['Preço do catálogo enviado: R$ 219,90','Marca: Rapoo','Modelo e disponibilidade: confirmar']},
{id:'gamer',name:'Fone Gamer para PC / PlayStation',category:'tech',type:'Headsets com fio',price:42900,image:"/images/gamer-hq.webp",imageSource:"https://www.panacompu.com/panama/en/product-information/razer-kraken-x-for-playstation-headset-wired-over-ear-headband-white",imageNote:"Foto de referência da linha Razer Kraken X branca. O título no catálogo está cortado; confirme a versão exata.",description:'Fone gamer apresentado no catálogo ICC. O título está parcialmente cortado na captura; confirme o modelo e compatibilidade com a equipe.',specs:['Preço do catálogo: R$ 429,00','Nome completo: confirmar','Compatibilidade específica: confirmar']},
{id:'redragon',name:'Fone Gamer Redragon Nireus',category:'tech',type:'Headsets com fio',price:33490,image:"/images/redragon-hq.webp",imageSource:"https://www.pichau.com.br/headset-gamer-redragon-nireus-rgb-som-surround-7-1-drivers-50mm-branco-h399w-rgb",imageNote:"Foto do Redragon Nireus branco. Confirme a variante e a disponibilidade com a ICC.",badge:'Seu próximo setup',description:'Headset gamer Redragon Nireus apresentado no catálogo ICC. Consulte as características e a disponibilidade com a loja.',specs:['Preço do catálogo: R$ 334,90','Marca: Redragon • linha Nireus','Disponibilidade: confirmar']},
{id:'pcyes',name:'Teclado Mecânico KLR Pcyes',category:'tech',type:'Teclados mecânicos',price:33990,image:"/images/pcyes-hq.webp",imageSource:"https://www.chipbyte.com.br/usb/teclado-mecanico-usb-pcyes-krl-vermelho-switch-outemu-blue/1752",imageNote:"Foto de referência do PCYes KLR. Confirme layout e switches com a loja.",description:'Teclado mecânico KLR Pcyes do catálogo ICC. Confirme layout, switches e compatibilidade antes do pedido.',specs:['Preço do catálogo: R$ 339,90','Marca: Pcyes','Layout e switches: confirmar']},
{id:'evolut',name:'Teclado Mecânico Evolut Pro…',category:'tech',type:'Teclados mecânicos',price:33990,image:"/images/evolut-hq.webp",imageSource:"https://www.ciapc.com.br/perifericos/mouse-teclado/teclado-mecanico-gamer-evolut-shodan-rgb-switch-red-preto-eg-203rg",imageNote:"Foto de referência da linha Evolut Shodan. O modelo completo não aparece no catálogo; confirme a versão com a ICC.",description:'Teclado mecânico Evolut do catálogo ICC. O nome está parcialmente cortado na captura; consulte o modelo completo.',specs:['Preço do catálogo: R$ 339,90','Modelo completo: confirmar','Layout e switches: confirmar']},
{id:'tdagger',name:'Teclado Mecânico T-Dagger B…',category:'tech',type:'Teclados mecânicos',price:31990,image:"/images/tdagger-hq.webp",imageSource:"https://www.t-dagger.com/products/t-dagger-bora-t-tgk315-gaming-mechanical-keyboard-rgb-backlighting",imageNote:"Foto de referência da linha T-Dagger Bora. Confirme modelo, layout e switches com a ICC.",description:'Teclado mecânico T-Dagger do catálogo ICC. O nome está parcialmente cortado; consulte o modelo completo com a equipe.',specs:['Preço do catálogo: R$ 319,90','Modelo completo: confirmar','Layout e switches: confirmar']},
{id:'logitech',name:'Kit Logitech MK235',category:'tech',type:'Kits sem fio',price:18990,image:"/images/logitech-hq.webp",imageSource:"https://www.logitech.com/pt-br/shop/p/mk235-durable-keyboard-mouse.920-007903",imageNote:"Foto oficial do Logitech MK235. A disposição das teclas pode variar por região.",badge:'Trabalho sem fios',description:'Kit de teclado e mouse sem fio Logitech MK235 apresentado no catálogo ICC. Consulte disponibilidade e detalhes.',specs:['Preço do catálogo: R$ 189,90','Marca: Logitech • modelo MK235','Kit teclado e mouse sem fio']},
...demonstration.filter(p=>p.category==='papelaria')
];
export const money = (cents: number) => (cents/100).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export const whatsapp = process.env.NEXT_PUBLIC_WHATSAPP || '553591791821';
export const wa = (text:string) => `https://wa.me/${whatsapp}?text=${encodeURIComponent(text)}`;
export const maps = 'https://www.google.com/maps/search/?api=1&query=ICC+Shopping+da+Informática+Av.+Rui+Barbosa+76+Varginha';
